# Generated by Django 5.2.7 on 2025-11-05 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_facultybooking_file_peripheralevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='pc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.pc'),
        ),
    ]
