# Generated by Django 5.2 on 2026-02-05 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_add_violation_suspension_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebFilterPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('blocklist', 'Blocklist'), ('allowlist', 'Allowlist')], default='blocklist', max_length=20)),
                ('domains', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webfilter_policy', to='main_app.pc')),
            ],
        ),
    ]
